== np_nifalcon Max/MSP and Pd External ==

by Kyle Machulis <kyle@nonpolynomial.com>

Nonpolynomial Labs - http://www.nonpolynomial.com

Contributors:

Edgar Berdahl
http://ccrma.stanford.edu/~eberdahl/

== Description ==

np_nifalcon is an external for either Max/MSP or Puredata to control the Novint Falcon. It is based on libnifalcon:

http://libnifalcon.nonpolynomial.com

Portability of source between Max and Pd is available thanks to flext

- Max: http://www.cycling74.com
- Pd: http://www.puredata.info
- Flext: http://puredata.info/Members/thomas/flext

== Novint Falcon Information ==

More information about the Novint Falcon can be found at 

- Product Website - http://home.novint.com
- libnifalcon Cross Platform Open Source driver - http://libnifalcon.nonpolynomial.com

== Installation ==

- Put the .mxo(Mac)/.mxe(Windows) or .pd_[platform] file in a directory that Max/Pd will search for externals (Max: Options -> File Preferences -> Other Folders, Pd: Options -> Paths)
- Max: Put the .help (Max4) or .maxhelp (Max5) file in the max-help directory of your Max/MSP installation

== Platform Specifics Issues ==

=== Windows ===

- Make sure the falcon is DIRECTLY CONNECTED to your machine. DO NOT go through a USB hub.

=== OS X ===

- Make sure the falcon IS NOT DIRECTLY CONNECTED TO YOUR MACHINE. ONLY CONNECT THROUGH A POWERED USB HUB.

=== Linux ===

- Make sure the falcon IS NOT DIRECTLY CONNECTED TO YOUR MACHINE. ONLY CONNECT THROUGH A POWERED USB HUB.
- np_nifalcon requires either root access (i.e. running pd under sudo) or correct udev based USB permissions to run as non-root. If you're using a udev based system, check out the udev sample files in the linux directory of the libnifalcon source distribution (v1.0 beta 1 and later)

== Licensing ==

np_nifalcon is covered under the BSD License, but since it's based on flext, it's GPL. Damn you, viral licensing.

Copyright
-------------------

np_nifalcon, Copyright 2007-2010 Kyle Machulis/Nonpolynomial Labs

-------------------

libnifalcon is covered under the BSD License.

Copyright
-------------------

libnifalcon, Copyright 2007-2009 Kyle Machulis/Nonpolynomial Labs

libnifalcon Kinematics Core, Copyright 2007-2008 Kevin Ouellet, 2009 Alastair Barrow, 2007-2009 Kyle Machulis

-------------------

flext source code are covered under the GPL v2 License. np_nifalcon is BSD, but since it's based on flext, it's GPL.

Copyright
-------------------

flext - C++ layer for Max/MSP and pd (pure data) externals
Copyright (C) 2001-2005 Thomas Grill

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
 
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

In the official flext distribution, the GNU General Public License is
in the file gpl.txt

--------------------
